# Generated by Django 3.1 on 2020-08-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('starting_bid', models.IntegerField()),
                ('image_url', models.CharField(max_length=128)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list', to='auctions.category')),
            ],
        ),
    ]
