# Generated by Django 3.1 on 2020-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200901_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing_id',
            field=models.IntegerField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
