# Generated by Django 3.1 on 2020-09-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_listing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bid', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
