# Generated by Django 3.1 on 2020-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200901_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
    ]
