# Generated by Django 3.1 on 2020-09-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
    ]
